Application/Beamer_shop/Beamer_shop/Pages/Account.cshtml.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Beamer_shop.Pages
{
    [Authorize]
    public class AccountModel : PageModel
    {
        public void OnGet()
        {
        }
        public async Task<IActionResult> OnPostAsync()
        {
            await HttpContext.SignOutAsync();
            return RedirectToPage("Login");
        }
    }
}

Application/Beamer_shop/Beamer_shop/Pages/CheckoutReview.cshtml.cs
using AutoMapper.Configuration;
using Factory.Interfaces;
using Logic;
using Logic.Interfaces;
using Logic.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using NuGet.Configuration;
using System;
using System.ComponentModel.DataAnnotations;
using ValidationContext = System.ComponentModel.DataAnnotations.ValidationContext;

namespace Beamer_shop.Pages
{
    [Authorize]
    public class CheckoutReviewModel : PageModel
    {
        private ICustomerFactory _customerFactory;
        private ICustomerService _customerService;

        private IDiscountFactory _discountFactory;
        private IDiscountService _discountService;

        private IOrderFactory _orderFactory;
        private IOrderService _orderService;

        public Customer? LoggedCustomer { get; set; }
        public Order? Order { get; set; }

        private JsonSerializerSettings settings = new JsonSerializerSettings
        {
            //Type hinting
            TypeNameHandling = TypeNameHandling.Auto
        };

        public CheckoutReviewModel(ICustomerFactory customerFactory, IDiscountFactory discountFactory, IOrderFactory orderFactory)
        {
            _customerFactory = customerFactory;
            _customerService = _customerFactory.CustomerService;

            _discountFactory = discountFactory;
            _discountService = _discountFactory.DiscountService;

            _orderFactory = orderFactory;
            _orderService = orderFactory.OrderService;
        }
        public IActionResult OnGet()
        {
            setupPage();

            Order.CalculateTotalTax();
            Order.CalculateTotalTotal();
            _=Order.ApplyDiscounts(_discountService.GetAllActiveDiscounts());

            tempOrder();

            return Page();


        }


        public IActionResult OnPostApplyCoupon()
        {
            var validationResult = setupPage();
            if(validationResult != null)
            {
                return validationResult;
            }

            if (Request.Form.TryGetValue("CouponCode", out var value))
            {
                string coupon = value.ToString();

                if(string.IsNullOrEmpty(coupon))
                {

                    tempOrder();

                    return throwError("/CheckoutReview", "Please enter a coupon code.");

                }

                if (!Order.ApplyDiscounts(_discountService.GetAllActiveDiscounts(), coupon))
                {
                    Order.DiscountsApplied.Clear();

                    tempOrder();

                    return throwError("/CheckoutReview", "Coupon not applicable.");

                }

                tempOrder();

                return Page();
            }

            tempOrder();

            return throwError("/CheckoutReview", "Please enter coupon code.");
        }

        public IActionResult OnPostCheckoutOrder()
        {
            var validationResult = setupPage();
            if (validationResult != null)
            {
                return validationResult;
            }

            var validationResults = new List<ValidationResult>();
            var validationContext = new ValidationContext(Order);
            Validator.TryValidateObject(Order, validationContext, validationResults);

            if (validationResults.Any()) { return throwError("/CheckoutInfo", "There has occured an error, please try again or contact us."); }

            int orderId;
            switch (Order.PaymentType)
            {
                case 0:
                    orderId = _orderService.MakeOrder(Order);
                    if (orderId > 0)
                    {
                        Order.Id = orderId;
                        tempOrder();
                        return Redirect("/PayCC");
                    }
                    else return throwError("/CheckoutInfo", "There has occured an error, please try again or contact us.");
   
                case 1:
                    orderId = _orderService.MakeOrder(Order);
                    if (orderId > 0)
                    {
                        Order.Id = orderId;
                        tempOrder();
                        return Redirect("/Account");
                    }
                    else return throwError("/CheckoutInfo", "There has occured an error, please try again or contact us.");

                default:
                    return throwError("/CheckoutInfo", "There has occured an error, please try again or contact us.");
            }

        }

        public IActionResult OnPostPaymentMethodCreditCard()
        {
            var validationResult = setupPage();
            if (validationResult != null)
            {
                return validationResult;
            }

            Order.PaymentType = 0;

            tempOrder();

            return Page();
        }

        public IActionResult OnPostPaymentMethodKlarna()
        {
            var validationResult = setupPage();
            if (validationResult != null)
            {
                return validationResult;
            }

            Order.PaymentType = 1;

            tempOrder();

            return Page();
        }

        private IActionResult? setupPage()
        {
            if (TempData.ContainsKey("preparedOrder"))
            {
                Order = JsonConvert.DeserializeObject<Order>(TempData["preparedOrder"].ToString(), settings);
            }
            

            if (Order == null) { return throwError("/CheckoutInfo", "Order not found."); }

            //check if user is logged in
            if (User?.Identity?.IsAuthenticated == false)
            {
                return throwError("/CheckoutInfo", "No user logged in.");
            }

            //get id of logged in user
            var idClaim = User.FindFirst("id");
            if (idClaim == null)
            {
                return throwError("/CheckoutInfo", "User not found.");
            }

            int idValue = Convert.ToInt32(idClaim.Value);

            //get user
            if ((LoggedCustomer = _customerService.GetCustomerById(idValue)) == null)
            {
                return throwError("/CheckoutInfo", "User not found.");
            }

            if (!LoggedCustomer.Equals(_customerService.GetCustomerById(idValue)))
            {
                return throwError("/CheckoutInfo", "Failed to match user with order.");
            }

            return null;
        }

        private void tempOrder()
        {
            //serialize order object
            var json = JsonConvert.SerializeObject(Order, settings);
            TempData["preparedOrder"] = json;
        }

        private IActionResult throwError(string page, string error)
        {
            TempData["ErrorMessage"] = error;
            return Redirect(page);
        }

    }
}

Application/Beamer_shop/Beamer_shop/Pages/CheckoutShip.cshtml.cs
using Beamer_shop.Interfaces;
using Beamer_shop.Models;
using Beamer_shop.Services;
using Factory;
using Factory.Interfaces;
using Logic;
using Logic.Interfaces;
using Logic.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using GoogleMaps.LocationServices;
using Address = Beamer_shop.Models.Address;
using Beamer_shop.Pages.Components;
using Newtonsoft.Json;
using NuGet.Configuration;

namespace Beamer_shop.Pages
{
    [Authorize]
    public class CheckoutShipModel : PageModel
    {
        private ICustomerFactory _customerFactory;
        private ICustomerService _customerService;
        private IShoppingCartService _shoppingCartService;

        [BindProperty]
        public Address ChangedShippingAddress { get; set; }
        public Address ShippingAddress { get; set; }

        public Customer? LoggedCustomer { get; set; }

        public IShoppingCart? ShoppingCart { get; set; }

        public IShippingCalculator ShippingCalculator { get; set; }


        private JsonSerializerSettings settings = new JsonSerializerSettings
        {
            //Type hinting
            TypeNameHandling = TypeNameHandling.Auto
        };

        public CheckoutShipModel(ICustomerFactory customerFactory, IShoppingCartService shoppingCartService)
        {
            _customerFactory = customerFactory;
            _customerService = _customerFactory.CustomerService;

            _shoppingCartService = shoppingCartService;
            ShoppingCart = _shoppingCartService.RetrieveShoppingCart();            
        }

        public IActionResult OnGet()
        {
            getUser();
            if (LoggedCustomer != null)
            {

                setAddress();
                if (!refreshShippingCost()) { TempData["ErrorMessage"] = "Your cart is empty."; return Redirect("/CheckoutInfo"); };
                return Page();
            }
            else
            {
                TempData["ErrorMessage"] = "No user logged in."; return Redirect("/CheckoutInfo");
            }


        }

        public IActionResult OnPostChangeShippingAddress()
        {
            getUser();
            ShippingAddress = ChangedShippingAddress;
            if(!refreshShippingCost()) { TempData["ErrorMessage"] = "Your cart is empty."; return Redirect("/CheckoutInfo"); };

            var json = JsonConvert.SerializeObject(ShippingAddress, settings);

            TempData["newShippingAddress"] = json;

            return Page();

        }

        public IActionResult OnPostPrepareOrder()
        {
            getUser();
            setAddress();
            var shippingAdress = TempData["newShippingAddress"];
            if(shippingAdress != null)
            {
                ShippingAddress = JsonConvert.DeserializeObject<Address>(shippingAdress.ToString());
            }

            if (LoggedCustomer == null)
            {
                TempData["ErrorMessage"] = "No user logged in."; return Redirect("/CheckoutInfo");
            }

            if(ShoppingCart == null || ShoppingCart.GetItems().Count < 1)
            {
                TempData["ErrorMessage"] = "Your cart is empty."; return Redirect("/CheckoutInfo");
            }

            if (!refreshShippingCost()) { TempData["ErrorMessage"] = "Update your delivery address."; return Redirect("/CheckoutInfo"); };

            Order prepOrder = new Order(ShoppingCart, LoggedCustomer.Id, 0, ShippingCalculator.EstimatedDeliveryTime.Item1, ShippingCalculator.EstimatedDeliveryTime.Item2, new Logic.Models.Address(ShippingAddress.Street, ShippingAddress.HouseNumber, ShippingAddress.City, ShippingAddress.Zipcode, ShippingAddress.Country), ShippingCalculator.TotalShippingCost);

            //serialize order object
            var json = JsonConvert.SerializeObject(prepOrder, settings);

            TempData["preparedOrder"] = json;
            return Redirect("/CheckoutReview");
        }

        private void getUser()
        {
            //get id of logged in user
            var idClaim = User.FindFirst("id");
            if (idClaim != null)
            {
                int idValue = Convert.ToInt32(idClaim.Value);
                LoggedCustomer = _customerService.GetCustomerById(idValue);
            }
        }

        public void setAddress()
        {
            ShippingAddress = new Address
            {
                Street = LoggedCustomer.Street,
                HouseNumber = LoggedCustomer.HouseNumber,
                City = LoggedCustomer.City,
                Zipcode = LoggedCustomer.ZipCode,
                Country = LoggedCustomer.Country
            };
        }
        
        private bool refreshShippingCost()
        {
            if (ShoppingCart == null) { return false; }
            
                try
                {
                    string address = ShippingAddress.Street + " " + ShippingAddress.HouseNumber;
                    ShippingCalculator = new ShippingCalculator(address, ShoppingCart);
                    return true;
                } catch
                {
                    return false;
                }
            
        }






    }
}

Application/Beamer_shop/Beamer_shop/Pages/Contact.cshtml.cs
using Logic.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Text.Json;

namespace Beamer_shop.Pages
{
    public class ContactModel : PageModel
    {
        [BindProperty]
        public Contact contact { get; set; }

        public IActionResult OnPost()
        {
            //filters
            if (ModelState.IsValid)
            {
                TempData["Contact"] = JsonSerializer.Serialize(contact);
                return new RedirectToPageResult("Index");
            }
            else
            {
                return Page();
            }
        }
        public void OnGet()
        {
        }
    }
}

Application/Beamer_shop/Beamer_shop/Pages/EditCart.cshtml.cs
using Logic.Models;
using Logic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Logic.Interfaces;
using Beamer_shop.Interfaces;

namespace Beamer_shop.Pages
{
    public class EditCart : PageModel
    {
        private IProductService _productService;
        private IShoppingCartService _shoppingCartService;
        private IShoppingCart? _shoppingCart = null;

        public EditCart(IProductService productService, IShoppingCartService shoppingCartService)
        {
            _productService = productService;
            _shoppingCartService = shoppingCartService;
        }

        public IActionResult OnGetAsync(int productId, string action)
        {

            //Check if id is valid
            if (productId <= 0 && action != "clear")
            {
                return BadRequest("Id not valid.");
            }

            //Check if product exists
            Product? product = _productService.getProductById(productId);
            if (product == null && action != "clear")
            {
                return NotFound("Product not found.");
            }

            _shoppingCart = _shoppingCartService.RetrieveShoppingCart();

            if(_shoppingCart == null) { return NotFound("Cart not found."); }


            //Switch for action
            switch (action)
            {
                case "add":
                    _shoppingCart.AddItem(product);
                    break;
                case "remove":
                    _shoppingCart.RemoveItem(product);
                    break;
                case "clear":
                    _shoppingCart.Clear();
                    break;
                default:
                    return BadRequest("Invalid action.");
            }

            //Try to save cart to session
            string result = _shoppingCartService.SaveShoppingCart(_shoppingCart);

            if (result.Length <= 0)
            {
                return BadRequest("Saving cart failed.");
            }
            else
            {
                //If success return cart in JSON format
                return new JsonResult(result);
            }
        }
    }
}

Application/Beamer_shop/Beamer_shop/Pages/Oops.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Beamer_shop.Pages
{
    public class OopsModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Application/Beamer_shop/Beamer_shop/Pages/Shop.cshtml.cs
using Beamer_shop.Interfaces;
using Beamer_shop.Services;
using Factory.Interfaces;
using Logic;
using Logic.Interfaces;
using Logic.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using System.Dynamic;
using System.Net.Http;
using System.Text;


namespace Beamer_shop.Pages
{
    public class ShopModel : PageModel
    {
        IProductFactory _productFactory;
        IProductService _productService;

        //Shopping cart
        public IShoppingCart? shoppingCart;
        private IShoppingCartService _shoppingCartService;

        [BindProperty]
        public ProductFilter? ProductFilter { get; set; }

        [BindProperty]
        public int? CartReceivedProductId { get; set; }

        public List<Product> storedProductCollection = new List<Product>();
        public List<Product> productCollection = new List<Product>();



        public ShopModel(IProductFactory productFactory, IShoppingCartService shoppingCartService)
        {
            _productFactory = productFactory;
            _productService = _productFactory.ProductService;
            productCollection.AddRange(_productService.GetAllProducts());

            storedProductCollection = productCollection;
            _shoppingCartService = shoppingCartService;
        }

        public void OnGet()
        {
            shoppingCart = _shoppingCartService.RetrieveShoppingCart();
            _shoppingCartService.SaveShoppingCart(shoppingCart);        
        }

        public void OnPostFilterProducts()
        {
            if (ProductFilter != null)
            {
                productCollection = ProductFilter.FilterProducts(storedProductCollection);
            }
        }

    }
}

Application/Beamer_shop/Beamer_shop/Pages/Account.cshtml
@page
@model Beamer_shop.Pages.AccountModel
@{
    ViewData["Title"] = "Account";
    ViewData["ActiveLink"] = "account";
}
<h1>Hello, <br /> @User.Identity.Name</h1>

<form method="post">
    <input type="submit" value="Log out" asp-page-handler="LogOut" />
</form>

Application/Beamer_shop/Beamer_shop/Pages/CheckoutReview.cshtml
@page
@using Logic;
@using Logic.Models
@model Beamer_shop.Pages.CheckoutReviewModel
@{
    ViewData["Title"] = "Checkout";
    ViewData["ActiveLink"] = "checkout";
}


<div id="bar-progress" class="mt-5 mt-lg-0">
    <div class="step step-active">
        <span class="number-container">
            <span class="number">1</span>
        </span>
        <h5>Login</h5>
    </div>
    <div class="seperator"></div>
    <div class="step step-active">
        <span class="number-container">
            <span class="number">2</span>
        </span>
        <h5>Confirm cart items</h5>
    </div>
    <div class="seperator"></div>
    <div class="step step-active">
        <span class="number-container">
            <span class="number">3</span>
        </span>
        <h5>Delivery</h5>
    </div>
    <div class="seperator"></div>
    <div class="step step-active">
        <span class="number-container">
            <span class="number">4</span>
        </span>
        <h5>Review &amp; Pay</h5>
    </div>
</div>

<div class="checkout-container" id="chk-ship-c">


    @if (User?.Identity?.IsAuthenticated ?? false)
    {
        @if (Model.LoggedCustomer != null)
        {
            Customer customer = Model.LoggedCustomer;

            <div class="chk-cbn-shp">
              
            <div class="chk-account-info">
                <h2>Buyer information:</h2>
                <h3>@customer.FirstName @customer.LastName</h3>
                <h3>@DateTime.Parse(customer.BirthDate).ToString("dd-MM-yyyy")</h3>
                <h3>@customer.Email</h3>
                <br>
                <h2>Buyer address:</h2>
                <h3>@customer.Street @customer.HouseNumber, @customer.City</h3>
                <h3>@customer.ZipCode, @customer.Country</h3>
            </div>

            
                @{ Address address = Model.Order.DeliveryAddress; }
            

            <div class="chk-account-shipping" id="seeShippingAdr">
                <h2 style="display:inline-block;">Shipping address: </h2> <br>
                <h3 style="display:inline;">@address.Street @address.HouseNumber, @address.City</h3>
                <h3>@address.Zipcode, @address.Country</h3>

                <br>

                <h2>Shipping:</h2>
                <h3>Cost: €@Model.Order.TotalShipping.ToString("N0")</h3>

                <h3>Estimated delivery: Between @Model.Order.EstimatedDeliveryA - @Model.Order.EstimatedDeliveryB days.</h3>


            </div>

            <div class="chk-pay-mthd">
                <h2>Select payment method</h2>
                    <div class="pay-mthd-cnt">

                        @if(Model.Order.PaymentType == 0){
                            <form asp-page-handler="PaymentMethodCreditCard" method="post">
                                <input value="" type="submit" class="pymnt-mthd-b" style="background-image: url(https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSy5WRZXYEU1ohkJBB7hNbkzm5McfqzIHSXew&usqp=CAU);border: 8px solid;outline-color: black;outline-style: solid;">
                            </form>
                            <form asp-page-handler="PaymentMethodKlarna" method="post">
                                <input value="" type="submit" class="pymnt-mthd-b" style="background-image: url(https://www.deadsailorbmx.co.uk/wp-content/uploads/2019/09/Klarna_ActionBadge_Secondary_Pink-700x420.png);">
                            </form>
                        }

                        @if (Model.Order.PaymentType == 1)
                        {
                            <form asp-page-handler="PaymentMethodCreditCard" method="post">
                                <input value="" type="submit" class="pymnt-mthd-b" style="background-image: url(https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSy5WRZXYEU1ohkJBB7hNbkzm5McfqzIHSXew&usqp=CAU);">
                            </form>
                            <form asp-page-handler="PaymentMethodKlarna" method="post">
                                <input value="" type="submit" class="pymnt-mthd-b" style="background-image: url(https://www.deadsailorbmx.co.uk/wp-content/uploads/2019/09/Klarna_ActionBadge_Secondary_Pink-700x420.png);border: 8px solid;outline-color: black;outline-style: solid;">
                            </form>
                        }


                    </div>
            </div>
            </div>
        }
    }

    <div class="checkout-cart-container">
        @{
            Order order = Model.Order;
        }
        <div class="checkout-cart">

            <h2>Overview</h2>
            <div class="chk-count-item">
                <h3>Products (@order.Items.GetItems().Count)</h3><h3>€@order.Items.Total.ToString("N0")</h3>
            </div>
            <div class="chk-count-item">
                <h3>Shipping</h3><h3>€@Math.Round(order.TotalShipping, 2).ToString("N0")</h3>
            </div>
            <div class="chk-count-item">
                <h3>Tax</h3><h3>€@Math.Round(order.TotalTax, 2).ToString("N0")</h3>
            </div>
            <hr>
             @{double subtotal = order.Items.Total + order.TotalShipping;}
            <h3>Subtotal: €@Math.Round(subtotal, 2).ToString("N0")</h3>
            <form asp-page-handler="ApplyCoupon" style="display: flex;align-items: baseline;gap:5px;">
                <input type="text" name="CouponCode" placeholder="Coupon"><input type="submit" value="Apply">
            </form>
            <hr />
            @{double _discount = 0; 
            if(order.Discount.HasValue) { _discount = Math.Round(order.Discount.Value, 2); } }
            <h4>Discount: €@_discount.ToString("N0")</h4>
            @if(_discount < 1) {
                <h2>Total: €@Math.Round(order.TotalTotal, 2).ToString("N0")</h2>
            } else {
                <h2 style="display:inline;">Total: </h2>
                <h2 style="display:inline;">€@Math.Round(order.TotalTotal, 2).ToString("N0")</h2>
                <h3 style="color:red; display:inline;text-decoration: line-through;">€@Math.Round(order.TotalTotal + _discount, 2).ToString("N0")</h3>
            }

        </div>

        <div class="checkout-price-details">

            <div class="cart-total">
                <form method="post" style="width: -webkit-fill-available;">
                    <input asp-page-handler="CheckoutOrder" value="Checkout" type="submit" style="width:inherit;">
                </form>
            </div>
        </div>
    </div>

</div>

Application/Beamer_shop/Beamer_shop/Pages/EditCart.cshtml
@page
@model Beamer_shop.Pages.EditCart
@{
}

Application/Beamer_shop/Beamer_shop/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home";
    ViewData["ActiveLink"] = "";
}

<img id="landing-car" src="/Images/bmwi8-home.png" alt="show-car" />

<div id="btnCollection">
    <a href="/Shop">View collection</a>
</div>

Application/Beamer_shop/Beamer_shop/Pages/Login.cshtml
@page
@model Beamer_shop.Pages.LoginModel
@{
    ViewData["Title"] = "Login";
    ViewData["ActiveLink"] = "account";
    

}

<div class="container">
<h3>Login</h3>
    <form method="post">
        <label asp-for="login.Email">Email</label>
        <span asp-validation-for="login.Email"></span>
        <input asp-for="login.Email" type="email" placeholder="Your email..">

        <label asp-for="login.Password">Password</label>
        <span asp-validation-for="login.Password"></span>
        <input asp-for="login.Password" type="password" placeholder="Your password..">

        <input type="submit" value="Log in">
        <h4>No account? <a href="/Register" style="text-decoration: underline; color: #117cec;">Sign up</a></h4>
    </form>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Application/Beamer_shop/Beamer_shop/Pages/Logout.cshtml
@page
@model WebApp.Pages.LogoutModel
@{
}

<div>
    <form method="post">
        <input type="submit" value="Log out" asp-page-handler="LogOut" />
    </form>
</div>

Application/Beamer_shop/Beamer_shop/Pages/MyOrders1.cshtml
@page
@using Logic.Models
@model Beamer_shop.Pages.MyOrders1Model
@{
}

@{
    Customer customer = Model.LoggedCustomer;
}

@foreach (Order order in Model.orders)
{
    <div class="ordr-order">
        <div class="chk-cbn-shp">

            <div class="chk-account-info">
                <h2>Buyer information:</h2>
                <h3>@customer.FirstName @customer.LastName</h3>
                <h3>@DateTime.Parse(customer.BirthDate).ToString("dd-MM-yyyy")</h3>
                <h3>@customer.Email</h3>
                <br>
                <h2>Buyer address:</h2>
                <h3>@customer.Street @customer.HouseNumber, @customer.City</h3>
                <h3>@customer.ZipCode, @customer.Country</h3>
            </div>


            @{
                Address address = order.DeliveryAddress;
            }


            <div class="chk-account-shipping" id="seeShippingAdr">
                <h2 style="display:inline-block;">Shipping address: </h2> <br>
                <h3 style="display:inline;">@address.Street @address.HouseNumber, @address.City</h3>
                <h3>@address.Zipcode, @address.Country</h3>

                <br>

                <h2>Shipping:</h2>
                <h3>Cost: €@order.TotalShipping.ToString("N0")</h3>

                <h3>Estimated delivery: Between @order.EstimatedDeliveryA - @order.EstimatedDeliveryB days.</h3>


            </div>

            <div class="chk-pay-mthd">
                <h2>Select payment method</h2>
                <div class="pay-mthd-cnt">

                    @if (order.PaymentType == 0)
                    {
                        <form asp-page-handler="PaymentMethodCreditCard" method="post">
                            <input value="" type="submit" class="pymnt-mthd-b" style="background-image: url(https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSy5WRZXYEU1ohkJBB7hNbkzm5McfqzIHSXew&usqp=CAU);border: 8px solid;outline-color: black;outline-style: solid;">
                        </form>
                        <form asp-page-handler="PaymentMethodKlarna" method="post">
                            <input value="" type="submit" class="pymnt-mthd-b" style="background-image: url(https://www.deadsailorbmx.co.uk/wp-content/uploads/2019/09/Klarna_ActionBadge_Secondary_Pink-700x420.png);">
                        </form>
                    }

                    @if (order.PaymentType == 1)
                    {
                        <form asp-page-handler="PaymentMethodCreditCard" method="post">
                            <input value="" type="submit" class="pymnt-mthd-b" style="background-image: url(https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSy5WRZXYEU1ohkJBB7hNbkzm5McfqzIHSXew&usqp=CAU);">
                        </form>
                        <form asp-page-handler="PaymentMethodKlarna" method="post">
                            <input value="" type="submit" class="pymnt-mthd-b" style="background-image: url(https://www.deadsailorbmx.co.uk/wp-content/uploads/2019/09/Klarna_ActionBadge_Secondary_Pink-700x420.png);border: 8px solid;outline-color: black;outline-style: solid;">
                        </form>
                    }


                </div>
            </div>
        </div>



        <div class="checkout-cart-container">
            <div class="checkout-cart">

                <h2>Overview</h2>
                <div class="chk-count-item">
                    <h3>Products (@order.Items.GetItems().Count)</h3><h3>€@order.Items.Total.ToString("N0")</h3>
                </div>
                <div class="chk-count-item">
                    <h3>Shipping</h3><h3>€@Math.Round(order.TotalShipping, 2).ToString("N0")</h3>
                </div>
                <div class="chk-count-item">
                    <h3>Tax</h3><h3>€@Math.Round(order.TotalTax, 2).ToString("N0")</h3>
                </div>
                <hr>
                @{
                    double subtotal = order.Items.Total + order.TotalShipping;
                }
                <h3>Subtotal: €@Math.Round(subtotal, 2).ToString("N0")</h3>
                <hr />
                @{
                    double _discount = 0;
                    if (order.Discount.HasValue) { _discount = Math.Round(order.Discount.Value, 2); }
                }
                <h4>Discount: €@_discount.ToString("N0")</h4>
                @if (_discount < 1)
                {
                    <h2>Total: €@Math.Round(order.TotalTotal, 2).ToString("N0")</h2>
                }
                else
                {
                    <h2 style="display:inline;">Total: </h2>
                    <h2 style="display:inline;">€@Math.Round(order.TotalTotal, 2).ToString("N0")</h2>
                    <h3 style="color:red; display:inline;text-decoration: line-through;">€@Math.Round(order.TotalTotal + _discount, 2).ToString("N0")</h3>
                }

            </div>
        </div>
    </div>
}

Application/Beamer_shop/Beamer_shop/Pages/Oops.cshtml
@page
@model Beamer_shop.Pages.OopsModel
@{
}
<h1 style="font-size:50px; color:red; font-weight:700; grid-column: 1 / 3; text-shadow: 2px 1px black;">
    Oops, something went wrong!
</h1>